language: ruby
rvm:
  - 2.5.1
install:
  - gem install bundler -v '1.16.2'
  - bundle install
script:
  - bundle exec jekyll build
  - bundle exec danger
env:
  - JEKYLL_ENV=production
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: _site
  target_branch: master
  on:
    branch: source