language: ruby
rvm:
  - 2.5.1
install:
  - bundle install
script:
  - bundle exec jekyll build
  - bundle exec danger
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: _site
  target_branch: master
  on:
    branch: source